config_version = 8

[backdrop]
blur_intensity = 0.019999999552965164
enabled = true

[bar.default]
background_opacity = 0.74999998323619366
center = [ "workspaces", "bar" ]
end = [ "group:g3", "clipboard", "group:g4", "notifications", "volume", "brightness", "group:g5" ]
margin_edge = 0
margin_ends = 0
radius = 0
radius_bottom_left = 80
radius_bottom_right = 80
start = [ "wallpaper", "nix-monitor", "recorder_2", "clock", "group:g2", "sysmon", "weather", "group:g6" ]

    [[bar.default.capsule_group]]
    border = ""
    enabled = true
    fill = "surface_variant"
    foreground = "primary"
    id = "g2"
    members = [ "cpu", "ram", "temp" ]
    opacity = 1.0
    padding = 10.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "audio_visualizer", "media" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "tray" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    foreground = "tertiary"
    id = "g5"
    members = [ "network", "bluetooth", "battery", "session" ]
    opacity = 1.0
    padding = 10.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    foreground = "tertiary"
    id = "g6"
    members = [ "notes", "todo", "launcher" ]
    opacity = 1.0
    padding = 8.0

[calendar]
enabled = true
refresh_minutes = 5

    [calendar.account.personal_google]
    name = "calendar"
    type = "google"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "dark_mode"

[[control_center.shortcuts]]
type = "media"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000006", "desktop-widget-0000000000000008", "desktop-widget-0000000000000009" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 272.1436767578125
    box_width = 386.0
    cx = 960.0
    cy = 480.58203125
    enabled = false
    output = "eDP-1"
    rotation = 0.0
    type = "sticker"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = true
        background_opacity = 0.45000000000000001
        background_padding = 5.0
        background_radius = 0.0
        image_path = "/home/requisite/Pictures/misc/Frieren_new_funny_thumbnail.webp"
        opacity = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000008]
    box_height = 141.203125
    box_width = 378.3828125
    cx = 1590.1640625
    cy = 786.37109375
    enabled = false
    output = "eDP-1"
    rotation = 0.0
    type = "label"

        [desktop_widgets.widget.desktop-widget-0000000000000008.settings]
        background = false
        description = "Actiate Noctlaia"
        opacity = 1.0
        title = "Activate Noctalia"

    [desktop_widgets.widget.desktop-widget-0000000000000009]
    box_height = 0.0
    box_width = 0.0
    cx = 234.28515625
    cy = 415.30859375
    output = "eDP-1"
    rotation = 0.0
    type = "noctalia/timer:timer"

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 957.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 879.984375
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 186.8125
    box_width = 437.6923828125
    cx = 960.0
    cy = 211.75
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        clock_style = "digital"
        color = "secondary"
        format = " {:%-I:%M %p}"
        shadow = false

[nightlight]
enabled = true
temperature_day = 10000

[notification]
blacklist = [ "tauon", "hyprshot" ]

[plugin_settings."avivbintangaringga/nix-monitor"]
branch = "nixos-unstable"
panel_open_near_click = false
panel_placement = "attached"
show_update_available_notification = false
update_command = "cd ~/nixos-dotfiles && nvim"

[plugin_settings."noctalia/notes"]
notes_dir = "~/Documents/talianotes"

[plugin_settings."noctalia/screen_recorder"]
audio_source = "both"
copy_to_clipboard = true
directory = "~/Videos"
video_source = "focused"

[plugin_settings."yocraft/web-launcher"]
links = [
    "literaturegirl|https://literaturegirl.neocities.org",
    "dotfiles|https://github.com/r3quisitevariety/nixos-dotfiles-2.0"
]

[plugins]
enabled = [
    "noctalia/screen_recorder",
    "noctalia/kaomoji",
    "noctalia/notes",
    "nightwatch75/todo",
    "avivbintangaringga/nix-monitor",
    "thepunkoff/pomodoro",
    "noctalia/timer",
    "yocraft/web-launcher"
]

[shell]
app_icon_color = "on_surface"
avatar_path = "/home/nix/Pictures/misc/b2e253dd2eb170b841469e4053bd15f1.jpg"
clipboard_confirm_clear_history = false
font_family = "Noto Sans"
niri_overview_type_to_launch_enabled = true
screen_time_enabled = true
settings_show_advanced = true
show_location = false
time_format = "{:%-I:%M %p}"

    [shell.panel]
    transparency_mode = "soft"

    [shell.screenshot]
    save_to_file = false

    [shell.shadow]
    alpha = 0.99999997764825821

[theme]
builtin = "Gruvbox"
community_palette = "Catppuccin Mocha Blue"
custom_palette = "m3-content"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-fruit-salad"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "mango", "niri", "qt" ]
    community_ids = [
        "opencode",
        "pywalfox",
        "zen-browser",
        "discord",
        "telegram",
        "neovim",
        "vscode",
        "steam",
        "fuzzel",
        "zathura",
        "hyprtoolkit",
        "yazi"
    ]

[wallpaper]
directory = "~/Pictures/wallpapers"
edge_smoothness = 0.0
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/nix/Pictures/wallpapers/moody/wallhaven-je95gq_1920x1080.png"

    [wallpaper.last]
    path = "/home/nix/Pictures/wallpapers/moody/wallhaven-je95gq_1920x1080.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/nix/Pictures/wallpapers/moody/wallhaven-je95gq_1920x1080.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/nix/Pictures/wallpapers/nature/wallhaven-dgdmj3.jpg"

[weather]
address = "Toronto, Canada"

[widget.active_window]
capsule = true

[widget.bar]
show_idle_on_horizontal = false
type = "noctalia/timer:bar"

[widget.battery]
display_mode = "graphic"
show_label = false

[widget.bluetooth]
show_label = true

[widget.bongocat]
script = "scripts/bongocat.lua"
type = "scripted"

[widget.brightness]
capsule = true
show_label = false

[widget.clipboard]
capsule = true

[widget.clock]
capsule = true
capsule_fill = "surface_variant"
capsule_foreground = "secondary"
enabled = false
format = "{:%A, %B %e, %Y, %I:%M %p}"

[widget.cpu]
show_label = false

[widget.launcher]
capsule = true

[widget.media]
album_art_only = true
hide_when_no_media = true
max_length = 100
min_length = 100

[widget.network]
show_label = false

[widget.nix-monitor]
capsule = true
colorize_glyph = false
show_text = false
type = "avivbintangaringga/nix-monitor:nix-monitor"

[widget.notes]
type = "noctalia/notes:notes"

[widget.notifications]
capsule = true

[widget.ram]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.recorder_2]
capsule = true
type = "noctalia/screen_recorder:recorder"

[widget.spacer_2]
type = "spacer"

[widget.spacer_3]
type = "spacer"

[widget.sysmon]
capsule = true
enabled = false
stat = "gpu_vram"

[widget.taskbar]
anchor = true
group_by_workspace = true

[widget.temp]
show_label = false

[widget.todo]
type = "nightwatch75/todo:todo"

[widget.tray]
capsule = true
drawer = true

[widget.volume]
capsule = true
show_label = false

[widget.wallpaper]
capsule = true

[widget.weather]
capsule = true
enabled = false

[widget.workspaces]
anchor = true
capsule_fill = "on_primary"
hide_when_empty = true